### ISSUE TITLE
session.SendFile/session.SendFileWithMessage: Always fails with a 401

### ISSUE THREAD

**Issue by Krognol** [Krognol/discordnim#1]

**Comment by Krognol** [comment]
It appears nim's standard post function puts the authorization header in the raw body instead of in the header of the client. How and why I have no idea.

**Comment by Krognol** [comment]
`SendFile` and `SendFileWithMessage` will work with an edit in the `httpclient` library.

**Comment by AjBreidenbach** [comment]
what changes exactly need to be made to the `httpclient` library to get this working?

**Comment by Krognol** [comment]
This should be fixed with the latest Nim release (`0.17`). But if you for some reason don't want to update [here's the relevant commit.](https://github.com/nim-lang/Nim/commit/5cf31417a6fcbe5a40bce792652fc05fc6a1cff9)

**Comment by AjBreidenbach** [comment]
Hey, thanks for the quick response.  I guess I don't know if this is the same issue or not, but I'm on 0.17

On line 59 of the GetGateway method it's unable to marshal the result
this is res.body: ```{"code": 0, "message": "401: Unauthorized"}```

this was specifically on the cache_messages.nim example

other examples typically crash possibly the same reason?

**Comment by Krognol** [comment]
Well this is strange. Last I tested it it worked fine. I'll look into it tomorrow morning.

**Comment by AjBreidenbach** [comment]
Hey, sorry about that, I had a typo on my bot key.  Only the basic bot is crashing.  I'll check it out tomorrow
