### ISSUE TITLE
Insane CPU usage

### ISSUE THREAD

**Issue by metagn** [Krognol/discordnim#14]
![look](https://7.lithi.io/D6Ac.png)

**Comment by Krognol** [comment]
I can't seem to reproduce this. I'm assuming you're using the latest version of both Nim and discordnim?

**Comment by metagn** [comment]
yes. bot is on 2 guilds

**Comment by Krognol** [comment]
If you're using the basic_bot example, did you change anything in the code?

**Comment by Krognol** [comment]
I've pushed some changes to the library. Update and check if that changes anything, I suppose.
