### ISSUE TITLE
Doesn't compile with nim 0.18.0

### ISSUE THREAD

**Issue by ShieldHero** [Krognol/discordnim#18]
I use 0.18.0 and I grabbed the current version of the dependencies, but it seems that it's a problem with the updated async library in nim itself, is there a chance to update this library?

**Comment by Krognol** [comment]
Do you get an error?

**Comment by ShieldHero** [comment]
I got it to compile, the problem was the function SendText in websocket, it no longer has a bool as a parameter, but now there's a crash, the test was done with basic_bot.nim, here's the crash message:

Traceback (most recent call last)
basic_bot.nim(20)        basic_bot
asyncdispatch.nim(1507)  waitFor
asyncdispatch.nim(1511)  poll
asyncdispatch.nim(350)   runOnce
asyncdispatch.nim(183)   processPendingCallbacks
asyncmacro.nim(34)       startSession_continue
discord.nim(494)         startSessionIter
discord.nim(427)         sessionHandleSocketMessage
discord.nim(194)         handleDispatch
asyncmacro.nim(401)      handleDispatch
asyncmacro.nim(34)       handleDispatch_continue
discord.nim(278)         handleDispatchIter
basic_bot.nim(7)         messageCreate
SIGSEGV: Illegal storage access. (Attempt to read from nil?)

**Comment by Krognol** [comment]
Looks like the message object may be uninitialized, or something within it.
