### ISSUE TITLE
s.channelMessageSend doesn't work for me

### ISSUE THREAD

**Issue by v3rmine** [Krognol/discordnim#19]
Hello,
I've tried a program of mine, and some of the examples, but I can't get `s.channelMessageSend` to work...
The program doesn't crash, it just does nothing. :/
I'm under the latest version of nim (`Nim Compiler Version 0.18.0 [Linux: amd64]`) and the latest version of discordnim too.

(I'm using a Manjaro 18.0)

Thanks for your advice ~

**Comment by Krognol** [comment]
Is your token correct? E.g. you created a new shard with `newShard("Bot my.Token")`?
Do you receive events from the websocket?
Do you have any example code of what you're trying to do?

**Comment by v3rmine** [comment]
Yep my token is working, I'm receiving events too but I cannot send anything :x
```nim
import discordnim, asyncdispatch, strutils, os, times

const token = "****"
const id = "****"

echo "https://discordapp.com/oauth2/authorize?client_id=", id,"&scope=bot&permissions=67628240"

proc matchesCommand*(m: MessageCreate, s: Shard, command: string): bool =
    if m.content.isNilOrEmpty(): return false

    var msg = m.content.toLowerAscii()
    result = (msg == command) or msg.startsWith(command.toLowerAscii() & " ")

proc someMessageCreateProc(s: Shard, m: MessageCreate) =
    if m.matchesCommand(s, "ping"):
        echo "ENTERED"
        asyncCheck s.channelMessageSend(m.channel_id,"pong!")

let client = newShard(token)
client.compress = true 

## Add your gateway event methods
discard client.addHandler(EventType.message_create, someMessageCreateProc)

## Lastly you connect
waitFor client.startSession()
```

**Comment by Krognol** [comment]
You need to prepend `Bot ` to your token.
Also you should reset your token.

**Comment by v3rmine** [comment]
I've reset my token but when I prepend my token with `Bot` (like `"Bot****"`),
the process exit with `Error: unhandled exception: invalid field name: code [ValueError]`.

**Comment by Krognol** [comment]
There needs to be a space in between "Bot" and your token, like in the examples; "Bot Token"

**Comment by v3rmine** [comment]
It works perfectly !
Thanks for your help ! :smile_cat:
